route:
  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: 'https://discord.com/api/webhooks/1341822671851225159/F_309qub8dfvqsKJuPGTqermJYaR5GjS6-gtPvUjMRJedDmGyQ48VYR3aVt17YKJ4G76'